default:
  tags:
    - docker

stages:
  - test
  - package

variables:
  IMAGE_NAME: storagegrid-usage-proxy

test:python36:
  stage: test
  image: "python:3.6.15-slim-buster"
  script:
    - python -m unittest discover -s tests -v

test:python311:
  stage: test
  image: "python:3.11-slim-bookworm"
  script:
    - python -m unittest discover -s tests -v

package:docker-offline:
  stage: package
  image: "docker:27.5.1-cli"
  needs:
    - test:python36
    - test:python311
  before_script:
    - docker info
    - sh .gitlab-ci-cd/pull-base-image.sh

  script:
    - sh .gitlab-ci-cd/package-docker-offline.sh

  artifacts:
    name: "storagegrid-usage-proxy-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    expire_in: 30 days
    paths:
      - storagegrid-usage-proxy_*.tar
      - storagegrid-usage-proxy_*.tar.sha256
      - IMAGE_VERSION.txt
      - .env
      - compose.yml

  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - TAG
