services:
  storagegrid-usage-proxy:
    image: storagegrid-usage-proxy:${IMAGE_TAG:?IMAGE_TAG must be set}
    container_name: storagegrid-usage-proxy
    restart: unless-stopped

    ports:
      - "8787:8787"

    volumes:
      - /mnt/storagegrid-uage-proxy/proxy.env:/app/config/proxy.env:ro
      - /mnt/storagegrid-uage-proxy/certs:/app/certs:ro

    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

    stop_grace_period: 15s